### ISSUE TITLE
MySQL Database support for playerdata

### ISSUE THREAD

**Issue by LadyHaley** [CCSKore/Pronouns#1]
### Describe what you want adding or changing

MySQL Database support for playerdata so that pronoun settings can be synced over multiple servers

**Comment by Novampr** [comment]
This plugin/mod links up with PronounDB, are you wanting the cache to be synced to a DB or do you want custom pronouns entirely separate from PronounDB, if it's the latter then that's out of the scope of this project unfortunately :(

**Comment by LadyHaley** [comment]
Im not talking about the pronoun list or anything like that, Im talking about the player data, for what pronouns a player wants to use, I want to store that information in a MySQL server so that all my servers can read the same players information, and so that the player only has to set their pronouns on one server, and have it show on all the servers.
I have a SQL server that I want to use

**Comment by Novampr** [comment]
All pronoun data is pulled from PronounDB, I store no data at all. I could consider a mode for [Pronouns 2](https://github.com/KoreDT/Pronouns2) which does local storage I suppose, more features wouldn't hurt. Pronouns2 isn't really done yet though

**Comment by LadyHaley** [comment]
I don't think you are understanding what I am asking.
With this plugin, as a minecraft player, when i run a command to set my pronouns, where does it save my settings for my username and UUID use she/her, it shouldnt be sending my minecraft UUID and pronouns back to the PronounDB or any other database not owned by the server owner, it has to save them somewhere on the minecraft server. What I am asking for, is to be able to change the location that is saves my minecraft accounts pronoun for the server I am on, to a MySQL database, that I have created, that I will connect all my servers up to, so that when I set my own personal pronouns on server 1, and then join server 2, server 2 will be able to already know what my pronouns are without having to set them a second time. you would not personally have to host a MySQL server for all users of the plugin to use, they would all have their own if they wanted to use mysql instead of the current data saving method. and optional addition

I dont know how to get my point accross any clearer if the above doesnt work. having MySQL data storage for plugins is very common, MySQLPlayerDataBridge is one good example a plugin that does it
https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/

**Comment by Novampr** [comment]
Currently the project stores nothing locally, you may have found the wrong GitHub repo perhaps? Also the project would never send pronouns to PronounDB, it only ever recieves from PronounDB. Would you mind sending me the link to where you got the Pronouns JAR from so I can verify this is my software and not someone else's?

**Comment by LadyHaley** [comment]
That is embarassing, my bad. I missed the part where it said it was an API. sorry about that

**Comment by Novampr** [comment]
No problem lol, happens sometimes

Enjoy pronoun searching!
